@hostname = 192.168.10.8
@port = 3888
@host = {{hostname}}:{{port}}
@contentType = 	application/json; charset=utf-8
@createdAt = {{$datetime 20200603}}

### Each request separated by '###',
### and the request can trigger by the button 'Send Request'

# @name index
GET http://{{host}} HTTP/1.1
Content-Type: {{contentType}}

###

# @name signin
POST http://{{host}}/auth/signin HTTP/1.1
Content-Type: {{contentType}}
# token: a4UIK78e5RdvHhTCOk4QSlULSzMrZ5Ia

{
    "name": "s1s",
    "password": "123"
}

###

# @name signup
POST http://{{host}}/auth/signup HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "dalao",
    "password": "123",
    "repassword": "123"
}

###

# @name certification
POST http://{{host}}/auth/certification HTTP/1.1
Content-Type: {{contentType}}

{
    "type": 0,
    "username": "liejy"
}
